version: 2.6.2
HuLa-IM:
  HOST: 127.0.0.1 #域名
  DATABASE_NAME: hula-im #数据库名
  MYSQL_USER_NAME: hula-im #数据库用户名
  MYSQL_PASSWORD: 123456 #数据库密码
  REDIS:
    PAW: mq0000 #redis密码, 如果是数字密码最好用引号包裹起来
    PORT: 16379 # redis端口号
  WX: # 微信配置
    CALLBACK: https://468ov9ww8878.vicp.fun
    APPID: wxb28a0fd6d1cae6ba
    SECRET: 9c215f8d078422805218221144b9095b
    TOKEN: nongyehong
    AESKEY: 7iNecFLZ8nbtCaMntHYEruSHP1Mk8FmGvrkHwnJzwug
  JWT: #JWT配置
    SECRET: dsfsdfsdfsdfsd
  ROCKETMQ: #rocketmq配置
    NAME-SERVER: 117.72.82.249:9876
    ACCESS-KEY: earthearth
    SECRET-KEY: mq000000
